name: publish

on:
  pull_request:
    branches: [source]
  push:
    branches: [source]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Test Build
        run: cd website && yarn install && yarn build
